// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// encode_sequences
Rcpp::IntegerVector encode_sequences(Rcpp::StringVector Seqs);
RcppExport SEXP _crio_encode_sequences(SEXP SeqsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type Seqs(SeqsSEXP);
    rcpp_result_gen = Rcpp::wrap(encode_sequences(Seqs));
    return rcpp_result_gen;
END_RCPP
}
// read_cell_barcodes
Rcpp::StringVector read_cell_barcodes(std::string fname, std::string dname, Rcpp::Nullable<Rcpp::IntegerVector> barcodelen);
RcppExport SEXP _crio_read_cell_barcodes(SEXP fnameSEXP, SEXP dnameSEXP, SEXP barcodelenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type dname(dnameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type barcodelen(barcodelenSEXP);
    rcpp_result_gen = Rcpp::wrap(read_cell_barcodes(fname, dname, barcodelen));
    return rcpp_result_gen;
END_RCPP
}
// write_cell_barcodes
SEXP write_cell_barcodes(Rcpp::StringVector barcodes, std::string fname, std::string dname);
RcppExport SEXP _crio_write_cell_barcodes(SEXP barcodesSEXP, SEXP fnameSEXP, SEXP dnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type dname(dnameSEXP);
    rcpp_result_gen = Rcpp::wrap(write_cell_barcodes(barcodes, fname, dname));
    return rcpp_result_gen;
END_RCPP
}
// read_mm
Rcpp::RObject read_mm(const std::string& path, bool two_pass, const std::string& class_name, int threads);
RcppExport SEXP _crio_read_mm(SEXP pathSEXP, SEXP two_passSEXP, SEXP class_nameSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type two_pass(two_passSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(read_mm(path, two_pass, class_name, threads));
    return rcpp_result_gen;
END_RCPP
}
// write_hdf5_counts
SEXP write_hdf5_counts(Rcpp::RObject ptr, std::string path, std::string group, bool is_integer, int num_threads);
RcppExport SEXP _crio_write_hdf5_counts(SEXP ptrSEXP, SEXP pathSEXP, SEXP groupSEXP, SEXP is_integerSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type group(groupSEXP);
    Rcpp::traits::input_parameter< bool >::type is_integer(is_integerSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(write_hdf5_counts(ptr, path, group, is_integer, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// write_mm
SEXP write_mm(Rcpp::RObject ptr, std::string path, bool compressed, bool is_integer, int num_threads);
RcppExport SEXP _crio_write_mm(SEXP ptrSEXP, SEXP pathSEXP, SEXP compressedSEXP, SEXP is_integerSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type compressed(compressedSEXP);
    Rcpp::traits::input_parameter< bool >::type is_integer(is_integerSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(write_mm(ptr, path, compressed, is_integer, num_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_crio_encode_sequences", (DL_FUNC) &_crio_encode_sequences, 1},
    {"_crio_read_cell_barcodes", (DL_FUNC) &_crio_read_cell_barcodes, 3},
    {"_crio_write_cell_barcodes", (DL_FUNC) &_crio_write_cell_barcodes, 3},
    {"_crio_read_mm", (DL_FUNC) &_crio_read_mm, 4},
    {"_crio_write_hdf5_counts", (DL_FUNC) &_crio_write_hdf5_counts, 5},
    {"_crio_write_mm", (DL_FUNC) &_crio_write_mm, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_crio(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
