# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

encode_sequences <- function(sequences) {
    .Call('_crio_encode_sequences', PACKAGE = 'crio', sequences)
}

decode_sequences <- function(encoded, lengths) {
    .Call('_crio_decode_sequences', PACKAGE = 'crio', encoded, lengths)
}

read_cell_barcodes <- function(fname, dname, barcodelen) {
    .Call('_crio_read_cell_barcodes', PACKAGE = 'crio', fname, dname, barcodelen)
}

write_cell_barcodes <- function(barcodes, fname, dname) {
    .Call('_crio_write_cell_barcodes', PACKAGE = 'crio', barcodes, fname, dname)
}

read_mm <- function(path, two_pass, class_name, threads) {
    .Call('_crio_read_mm', PACKAGE = 'crio', path, two_pass, class_name, threads)
}

write_hdf5_counts <- function(ptr, path, group, is_integer, num_threads) {
    .Call('_crio_write_hdf5_counts', PACKAGE = 'crio', ptr, path, group, is_integer, num_threads)
}

write_mm <- function(ptr, path, compressed, is_integer, num_threads) {
    .Call('_crio_write_mm', PACKAGE = 'crio', ptr, path, compressed, is_integer, num_threads)
}

