# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

encode_sequences <- function(Seqs) {
    .Call('_crio_encode_sequences', PACKAGE = 'crio', Seqs)
}

get_cell_barcodes <- function(fname, dname, barcodelen) {
    .Call('_crio_get_cell_barcodes', PACKAGE = 'crio', fname, dname, barcodelen)
}

